### ISSUE TITLE
Problem vith CFITSIO

### ISSUE THREAD

**Issue by BiavaNadia** [jeremysanders/ggm#2]
Goodmorning,

I'm trying to use adaptive_ggm.py, but I obtain a problem with CFITSIO:

ERROR: Mismatch in the CFITSIO_SONAME value in the fitsio.h include file
that was used to build the CFITSIO library, and the value in the include file
that was used when compiling the application program:
   Version used to build the CFITSIO library   = 2
   Version included by the application program = 9

Fix this by recompiling and then relinking this application program 
with the CFITSIO library.
FITSIO operation failed when:
 Opening file (RO)
Filename:
 2205_dmfilth_broad_thresh.fits

FITSIO status = 104: could not open the named file
Traceback (most recent call last):
  File "./adaptive_ggm.py", line 116, in <module>
    main()
  File "./adaptive_ggm.py", line 83, in main
    call(program, *cargs)
  File "./adaptive_ggm.py", line 29, in call
    subprocess.check_call(args)
  File "/home/nadia/.local/anaconda3/envs/ciao-4.13/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '('accumulate_counts', '2205_dmfilth_broad_thresh.fits', '--scale=scale.fits', '--sn=25', '--threads=4')' returned non-zero exit status 1.

I tried both using the original Makefile of contbin or with a modified version indicating the location of fitsio.h as follow, but I always obtain the same error.

# add -Ldirname to add directory to link path to look for cfitsio
linkflags=-L/home/nadia/Software/cfitsio-4.1.0 -lcfitsio -Lparammm -lparammm -lpthread

# where to install (not very well tested)
bindir=/usr/bin

# sensible compiler flags
export CXXFLAGS=-I/usr/include -O2 -g -Wall -std=c++11
export CXX=g++

Do you have some suggestions?

Thanks,
Nadia

**Comment by jeremysanders** [comment]
Hi Nadia - it looks like there's an inconsistency between the location of CFITSIO in the header files and the library for contbin. You could try telling the compiler where the header files for cfitiso are when compiling by adding `-I/dir/name/` to CXXFLAGS. Make sure your cfitsio is properly installed - you need the directory where the .a or .so files are in linkflags, and the directory where the fitsio.h is in CXXFLAGS.

You may also need to make sure that the cfitsio installed location is in the link library path on linux (`ldd /path/to/contbin` will tell you which library it is using, if it's a shared library).

**Comment by BiavaNadia** [comment]
Problem solved, I was linking in both the cases to the directory where the fitsio.h file is, and not to the .so file in linkflags.

Many thanks,
Nadia

**Comment by jeremysanders** [comment]
Great!
